# Here you can define all coin types with their respective values
# For example, "copper = 1" (without quotes) creates a mercantile:copper_coin item with a value of 1

copper = 1
silver = 100
gold = 2500

# GUI related settings

retrieve_coin_button_width = 14
retrieve_coin_button_height = 13
retrieve_coin_button_icon_offset_x = -1
retrieve_coin_button_icon_offset_y = -2

coin_texture_size = 16

# If you add a new coin type, you'll also have to define the offsets for the button in the inventory below
# (for both survival and creative inventory)

copper_retrieve_coin_button_offset_x = 77
copper_retrieve_coin_button_offset_y = 7
copper_retrieve_coin_button_creative_offset_x = 127
copper_retrieve_coin_button_creative_offset_y = 5

silver_retrieve_coin_button_offset_x = 77
silver_retrieve_coin_button_offset_y = 21
silver_retrieve_coin_button_creative_offset_x = 127
silver_retrieve_coin_button_creative_offset_y = 19

gold_retrieve_coin_button_offset_x = 77
gold_retrieve_coin_button_offset_y = 35
gold_retrieve_coin_button_creative_offset_x = 127
gold_retrieve_coin_button_creative_offset_y = 33
