#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 20 20:22:21 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=Stracciatella Shaders v1.6.4.1 by DrDesten.zip
enableShaders=false
